//! N-body gravitational interaction between vessels.
//!
//! Force ∝ G·m₁·m₂ / r². This module computes forces between
//! all vessel pairs and detects stable configurations.

use serde::{Deserialize, Serialize};
use crate::vessel::Vessel;

/// A gravitational field generated by all vessels.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct GravitationalField {
    pub sources: Vec<Vessel>,
    pub G: f64,
}

impl GravitationalField {
    pub fn new(sources: Vec<Vessel>, g: f64) -> Self {
        Self { sources, G: g }
    }

    /// Gravitational force between two vessels: F = G·m₁·m₂ / r²
    /// Returns force vector on vessel_a due to vessel_b.
    pub fn force_between(&self, a: &Vessel, b: &Vessel) -> Vec<f64> {
        let dist = a.distance_to(b);
        if dist < 1e-10 {
            return vec![0.0; a.dimensions()];
        }
        let magnitude = self.G * a.mass * b.mass / (dist * dist);
        let direction: Vec<f64> = b.position.iter()
            .zip(a.position.iter())
            .map(|(bp, ap)| bp - ap)
            .collect();
        let norm: f64 = direction.iter().map(|d| d * d).sum::<f64>().sqrt();
        direction.iter().map(|d| magnitude * d / norm).collect()
    }

    /// Total gravitational force on a vessel from all others.
    pub fn net_force(&self, vessel: &Vessel) -> Vec<f64> {
        let dim = vessel.dimensions();
        self.sources.iter()
            .filter(|s| s.name != vessel.name)
            .fold(vec![0.0; dim], |acc, other| {
                let f = self.force_between(vessel, other);
                acc.iter().zip(f.iter()).map(|(a, b)| a + b).collect()
            })
    }

    /// Gravitational potential energy between all pairs.
    /// PE = -G·m₁·m₂ / r for each pair.
    pub fn total_potential_energy(&self) -> f64 {
        let mut pe = 0.0;
        for i in 0..self.sources.len() {
            for j in (i + 1)..self.sources.len() {
                let r = self.sources[i].distance_to(&self.sources[j]);
                if r > 1e-10 {
                    pe -= self.G * self.sources[i].mass * self.sources[j].mass / r;
                }
            }
        }
        pe
    }

    /// Gravitational potential at a point due to all sources.
    pub fn potential_at(&self, point: &[f64]) -> f64 {
        let dummy = Vessel::at("_point", 0.0, point.to_vec());
        self.sources.iter()
            .map(|s| {
                let r = dummy.distance_to(s);
                if r > 1e-10 { -self.G * s.mass / r } else { 0.0 }
            })
            .sum()
    }

    /// Compute accelerations for all vessels.
    pub fn accelerations(&self) -> Vec<Vec<f64>> {
        self.sources.iter()
            .map(|v| {
                let force = self.net_force(v);
                force.iter().map(|f| f / v.mass).collect()
            })
            .collect()
    }
}

/// Detect if a configuration of two vessels is a stable circular orbit.
/// For circular orbit: centripetal force = gravitational force.
pub fn is_circular_orbit(a: &Vessel, b: &Vessel, G: f64) -> bool {
    if a.dimensions() < 2 || b.dimensions() < 2 { return false; }
    let dist = a.distance_to(b);
    if dist < 1e-10 { return false; }

    // Relative velocity perpendicular to position
    let rel_v: Vec<f64> = b.velocity.iter().zip(a.velocity.iter()).map(|(bv, av)| bv - av).collect();
    let rel_r: Vec<f64> = b.position.iter().zip(a.position.iter()).map(|(bp, ap)| bp - ap).collect();

    // Radial component of velocity
    let dot: f64 = rel_v.iter().zip(rel_r.iter()).map(|(v, r)| v * r).sum();
    let r_mag_sq: f64 = rel_r.iter().map(|r| r * r).sum();

    // For circular orbit, radial velocity should be ~0
    let radial_v = (dot / r_mag_sq).abs();
    if radial_v > 1e-6 { return false; }

    // Check if v² / r ≈ G*M/r² (centripetal = gravitational)
    let v_sq: f64 = rel_v.iter().map(|v| v * v).sum();
    let total_mass = a.mass + b.mass;
    let expected_v_sq = G * total_mass / dist;

    (v_sq - expected_v_sq).abs() < 0.1 * expected_v_sq.max(1e-10)
}

/// Check if three vessels form a Lagrange-like equilateral triangle.
pub fn is_lagrange_triangle(a: &Vessel, b: &Vessel, c: &Vessel) -> bool {
    let d_ab = a.distance_to(b);
    let d_bc = b.distance_to(c);
    let d_ca = c.distance_to(a);
    let avg = (d_ab + d_bc + d_ca) / 3.0;
    if avg < 1e-10 { return false; }
    let tolerance = 0.1;
    (d_ab - avg).abs() / avg < tolerance
        && (d_bc - avg).abs() / avg < tolerance
        && (d_ca - avg).abs() / avg < tolerance
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gravitational_force_two_vessels() {
        let a = Vessel::at("A", 10.0, vec![0.0, 0.0]);
        let b = Vessel::at("B", 10.0, vec![2.0, 0.0]);
        let field = GravitationalField::new(vec![a.clone(), b.clone()], 1.0);
        let force = field.force_between(&a, &b);
        // F = G*m1*m2/r² = 1*10*10/4 = 25, direction (1, 0)
        assert!((force[0] - 25.0).abs() < 1e-10);
        assert!(force[1].abs() < 1e-10);
    }

    #[test]
    fn force_newtons_third_law() {
        let a = Vessel::at("A", 5.0, vec![0.0, 0.0]);
        let b = Vessel::at("B", 3.0, vec![1.0, 0.0]);
        let field = GravitationalField::new(vec![a.clone(), b.clone()], 2.0);
        let f_ab = field.force_between(&a, &b);
        let f_ba = field.force_between(&b, &a);
        assert!((f_ab[0] + f_ba[0]).abs() < 1e-10);
        assert!((f_ab[1] + f_ba[1]).abs() < 1e-10);
    }

    #[test]
    fn potential_energy_negative() {
        let a = Vessel::at("A", 10.0, vec![0.0, 0.0]);
        let b = Vessel::at("B", 10.0, vec![1.0, 0.0]);
        let field = GravitationalField::new(vec![a, b], 1.0);
        let pe = field.total_potential_energy();
        assert!(pe < 0.0);
    }

    #[test]
    fn net_force_zero_at_center_of_equal_pair() {
        let a = Vessel::at("A", 10.0, vec![-1.0, 0.0]);
        let b = Vessel::at("B", 10.0, vec![1.0, 0.0]);
        let c = Vessel::at("C", 1.0, vec![0.0, 0.0]);
        let field = GravitationalField::new(vec![a, b, c.clone()], 1.0);
        let f = field.net_force(&c);
        assert!(f[0].abs() < 1e-10);
    }

    #[test]
    fn circular_orbit_detection() {
        // Set up a circular orbit: v² = GM/r
        let g: f64 = 1.0;
        let r: f64 = 5.0;
        let total_mass: f64 = 20.0;
        let v: f64 = (g * total_mass / r).sqrt();
        let a = Vessel::with_velocity("A", 10.0, vec![0.0, 0.0], vec![0.0, 0.0]);
        let b = Vessel::with_velocity("B", 10.0, vec![r, 0.0], vec![0.0, v]);
        assert!(is_circular_orbit(&a, &b, g));
    }

    #[test]
    fn non_circular_orbit_detected() {
        let a = Vessel::at("A", 10.0, vec![0.0, 0.0]);
        let b = Vessel::with_velocity("B", 10.0, vec![5.0, 0.0], vec![100.0, 0.0]);
        assert!(!is_circular_orbit(&a, &b, 1.0));
    }

    #[test]
    fn lagrange_triangle_equilateral() {
        let s3 = 3.0_f64.sqrt();
        let a = Vessel::at("A", 10.0, vec![0.0, 0.0]);
        let b = Vessel::at("B", 10.0, vec![2.0, 0.0]);
        let c = Vessel::at("C", 10.0, vec![1.0, s3]);
        assert!(is_lagrange_triangle(&a, &b, &c));
    }

    #[test]
    fn not_lagrange_triangle() {
        let a = Vessel::at("A", 10.0, vec![0.0, 0.0]);
        let b = Vessel::at("B", 10.0, vec![1.0, 0.0]);
        let c = Vessel::at("C", 10.0, vec![10.0, 10.0]);
        assert!(!is_lagrange_triangle(&a, &b, &c));
    }

    #[test]
    fn potential_at_point() {
        let a = Vessel::at("A", 100.0, vec![0.0, 0.0]);
        let field = GravitationalField::new(vec![a], 1.0);
        let phi = field.potential_at(&[10.0, 0.0]);
        assert!((phi - (-10.0)).abs() < 1e-10);
    }

    #[test]
    fn accelerations_inverse_mass() {
        let a = Vessel::at("A", 1.0, vec![0.0, 0.0]);
        let b = Vessel::at("B", 100.0, vec![1.0, 0.0]);
        let field = GravitationalField::new(vec![a.clone(), b.clone()], 1.0);
        let accs = field.accelerations();
        // Heavier vessel has smaller acceleration
        let acc_a_mag = accs[0].iter().map(|x| x * x).sum::<f64>().sqrt();
        let acc_b_mag = accs[1].iter().map(|x| x * x).sum::<f64>().sqrt();
        assert!(acc_a_mag > acc_b_mag);
    }

    #[test]
    fn serde_roundtrip_field() {
        let field = GravitationalField::new(
            vec![Vessel::at("A", 10.0, vec![1.0, 2.0])],
            6.674e-11,
        );
        let json = serde_json::to_string(&field).unwrap();
        let f2: GravitationalField = serde_json::from_str(&json).unwrap();
        assert_eq!(field, f2);
    }
}
